---
- name: Test Ios Facts
  connection: network_cli
  hosts: all
  tasks:
    - name: Test
      ios_facts:
        gather_subset: interfaces
      register: all_subset
    - name: Print subset all
      debug:
        var: all_subset.ansible_facts.ansible_net_neighbors
