---
- name: Test Ios Facts
  connection: network_cli
  hosts: all
  tasks:
    - name: Delete VLANs
      ios_vlans:
        config:
        - vlan_id: 2
        - vlan_id: 3
        - vlan_id: 4
        - vlan_id: 5
        - vlan_id: 6
        - vlan_id: 7
        - vlan_id: 8
        - vlan_id: 9
        - vlan_id: 10
        - vlan_id: 20
        - vlan_id: 30
        state: deleted

