---
- name: Test Ios Facts
  connection: network_cli
  hosts: all
  tasks:
    - name: Delete VLANs
      ios_vlans:
        config:
        - vlan_id: 10
        - vlan_id: 20
        - vlan_id: 30
        state: deleted

