---
- name: Test Ios Facts
  connection: network_cli
  hosts: all
  tasks:
    - name: Delete VLANs

      ios.ios_vlans:
        config:
        - vlan_id: 10
        - vlan_id: 20
        - vlan_id: 30
        - vlan_id: 40
        - vlan_id: 50
        - vlan_id: 60
        state: deleted

