---
- name: Push configuration to switch
  vars:
    ansible_connection: network_cli
  gather_facts: false
  hosts: all
  become: yes
  become_method: enable
  tasks:
    - name: Create VLANs
      ios_vlans:
        config:
        - name: Vlan_10Access
          vlan_id: 10
          state: active
          shutdown: disabled
        - name: Vlan_20Access
          vlan_id: 20
          state: active
          shutdown: enabled
        - name: Vlan_30Access
          vlan_id: 30
        state: merged
    - name: Push config
      ios_config:
        src: "/etc/ansible/AnaSeguros/Respaldos/20230221/AccessSwitch.txt"
    - name: Save running
      ios_config:
        save_when: modified
