---
- name: Push configuration to switch
  vars:
    ansible_connection: network_cli
  gather_facts: false
  hosts: all
  become: yes
  become_method: enable
  tasks:
    - name: Push config
      ios_config:
        src: "/etc/ansible/AnaSeguros/Respaldos/20230221/DataCenterSwitch.txt"
    - name: Save running
      ios_config:
        save_when: modified

