---
- name: Test Ios Facts
  connection: network_cli
  hosts: all
  tasks:
    - name: Gathered
      cisco.ios.ios_vlans:
        config:
        state: gathered
      register: all_vlans
    - name: Print all vlans
      debug:
        msg: 
        - "nombre: {{ item.name }}"
        - "ID:{{ item.vlan_id }}"
      loop: "{{ all_vlans.gathered }}"
