---
- name: Test Ios Facts
  connection: network_cli
  hosts: all
  tasks:
    - name: Gathered
      ios_vlans:
        config:
        - name: VLAN30
          vlan_id: 30
          state: suspend
          shutdown: enabled
        state: merged      
      register: all_vlans
    - name: Print all vlans
      debug:
        msg: 
        - "nombre: {{ item.name }}"
        - "ID:{{ item.vlan_id }}"
      loop: "{{ all_vlans.gathered }}"
