---
- name: Test Ios Facts
  vars:
    ansible_connection: network_cli
  gather_facts: false
  hosts: all
  become: yes
  become_method: enable
  tasks:
    - name: Gathered
      ios_vlans:
        config:
        state: gathered
      register: all_vlans
    - name: Print all vlans
      debug:
        msg: 
        - "nombre: {{ item.name }}"
        - "ID:{{ item.vlan_id }}"
      loop: "{{ all_vlans.gathered }}"
