---
- name: VTP
  connection: network_cli
  hosts: all
  gather_facts: false
  become: yes
  become_method: enable
  tasks:
    - name: show VTP domain
      ios_command:
        commands:
          - show vtp status | include VTP Domain Name
          - show vtp status | include VTP Operating Mode 
      register: config
    - name: print output
      debug:
        msg: 
        - "{{ config.stdout }}"
